#!/usr/bin/env node
/**
 * Init Project — Tao CLAUDE.md tu repo scan
 *
 * Scan project → tong hop stack, scripts, structure → xuat CLAUDE.md
 * CLAUDE.md duoc Claude Code / Claude Agent SDK auto-load khi lam viec trong repo.
 *
 * Tuong tu: Claude Code /init command.
 */

const fs = require('fs');
const path = require('path');
const { RepoMapper } = require('./repo-mapper');

/**
 * Generate CLAUDE.md
 * @param {string} projectDir
 * @param {Object} opts - { force: ghi de neu co san }
 * @returns {Promise<{ created: boolean, path: string, reason?: string, content?: string }>}
 */
async function initProject(projectDir, opts = {}) {
  const targetPath = path.join(projectDir, 'CLAUDE.md');

  if (fs.existsSync(targetPath) && !opts.force) {
    return {
      created: false,
      path: targetPath,
      reason: 'CLAUDE.md already exists. Use --force to overwrite.'
    };
  }

  const mapper = new RepoMapper({ projectDir });
  const { projectType, exports: exportMap, summary } = await mapper.scan();

  const projectName = path.basename(projectDir);

  // Detect package.json info
  let pkgInfo = null;
  try {
    const pkgPath = path.join(projectDir, 'package.json');
    if (fs.existsSync(pkgPath)) {
      pkgInfo = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
    }
  } catch {}

  // Detect git info
  let gitInfo = null;
  try {
    const { execFileSync } = require('child_process');
    const branch = execFileSync('git', ['rev-parse', '--abbrev-ref', 'HEAD'], {
      cwd: projectDir, encoding: 'utf-8', stdio: ['ignore', 'pipe', 'ignore'], timeout: 2000
    }).trim();
    gitInfo = { branch };
  } catch {}

  // Compose CLAUDE.md
  const lines = [];
  lines.push(`# ${projectName}`);
  lines.push('');
  lines.push(`> ${projectType} project${pkgInfo?.description ? ` — ${pkgInfo.description}` : ''}`);
  lines.push('');

  // Quick facts
  lines.push('## Stack');
  lines.push(`- Project type: ${projectType}`);
  if (pkgInfo?.engines?.node) lines.push(`- Node: ${pkgInfo.engines.node}`);
  if (pkgInfo?.type) lines.push(`- Module: ${pkgInfo.type}`);
  if (gitInfo?.branch) lines.push(`- Current branch: \`${gitInfo.branch}\``);
  lines.push('');

  // Scripts
  if (pkgInfo?.scripts && Object.keys(pkgInfo.scripts).length > 0) {
    lines.push('## Scripts');
    for (const [name, cmd] of Object.entries(pkgInfo.scripts)) {
      lines.push(`- \`npm run ${name}\`: \`${cmd.slice(0, 80)}${cmd.length > 80 ? '...' : ''}\``);
    }
    lines.push('');
  }

  // Key files
  const keyFiles = [];
  if (fs.existsSync(path.join(projectDir, 'package.json'))) keyFiles.push('package.json');
  if (fs.existsSync(path.join(projectDir, 'tsconfig.json'))) keyFiles.push('tsconfig.json');
  if (fs.existsSync(path.join(projectDir, 'next.config.js'))) keyFiles.push('next.config.js');
  if (fs.existsSync(path.join(projectDir, 'vite.config.ts')) || fs.existsSync(path.join(projectDir, 'vite.config.js'))) keyFiles.push('vite.config');
  if (fs.existsSync(path.join(projectDir, 'Dockerfile'))) keyFiles.push('Dockerfile');
  if (fs.existsSync(path.join(projectDir, 'docker-compose.yaml')) || fs.existsSync(path.join(projectDir, 'docker-compose.yml'))) keyFiles.push('docker-compose.yaml');
  if (fs.existsSync(path.join(projectDir, '.env.example'))) keyFiles.push('.env.example');
  if (keyFiles.length > 0) {
    lines.push('## Key files');
    keyFiles.forEach(f => lines.push(`- \`${f}\``));
    lines.push('');
  }

  // Structure
  lines.push('## Structure');
  lines.push('```');
  lines.push(summary.split('\n').slice(0, 40).join('\n'));
  lines.push('```');
  lines.push('');

  // Top exports
  const exportEntries = Object.entries(exportMap || {}).slice(0, 10);
  if (exportEntries.length > 0) {
    lines.push('## Key exports');
    for (const [file, names] of exportEntries) {
      lines.push(`- \`${file}\`: ${names.slice(0, 5).join(', ')}`);
    }
    lines.push('');
  }

  // Conventions placeholder
  lines.push('## Conventions');
  lines.push('<!-- Fill in: code style, branch naming, PR workflow, test expectations -->');
  lines.push('');
  lines.push('## Working with AI agents');
  lines.push('- Run tests before declaring work done.');
  lines.push('- Keep commits atomic and message-descriptive.');
  lines.push('- Business logic comments in Vietnamese, technical comments in English.');
  lines.push('');
  lines.push('---');
  lines.push('_Generated by orcai /init — edit to fit your project._');
  lines.push('');

  const content = lines.join('\n');
  fs.writeFileSync(targetPath, content, 'utf-8');

  return {
    created: true,
    path: targetPath,
    content,
    stats: { lines: lines.length, bytes: content.length }
  };
}

module.exports = { initProject };
