#!/bin/bash
# setup-pod.sh — Install Python deps on pod into /workspace/pypkgs (persists
# across migrations) and write /workspace/setup-env.sh for training scripts.
#
# Usage:
#   POD_HOST=1.2.3.4 POD_PORT=12345 ./setup-pod.sh
#   # or, if .orcai/pod-info.txt exists, just: ./setup-pod.sh
#
# Exit codes: 0=ok, 2=ssh-fail, 3=deps-fail
#
# Rationale (Round 5.5 BUG 3): container disk is wiped on pod migration but
# /workspace (volume) persists. We install all deps with --target=/workspace/pypkgs
# so they survive "Start using CPUs" and host transfers. Training scripts just
# `source /workspace/setup-env.sh` to get PYTHONPATH + HF_HOME set.

set -u

SSH_KEY="$HOME/.ssh/id_ed25519"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
INFO_FILE="$ROOT/.orcai/pod-info.txt"

log() { echo "[$(date +%FT%T)] $*"; }

# ---- Load POD_HOST / POD_PORT (env overrides file) ----
if [ -z "${POD_HOST:-}" ] || [ -z "${POD_PORT:-}" ]; then
  if [ -f "$INFO_FILE" ]; then
    # shellcheck disable=SC1090
    . "$INFO_FILE"
  fi
fi
if [ -z "${POD_HOST:-}" ] || [ -z "${POD_PORT:-}" ]; then
  log "ERROR: POD_HOST/POD_PORT not set (env or $INFO_FILE)"; exit 2
fi

SSH_OPTS="-i $SSH_KEY -p $POD_PORT \
  -o StrictHostKeyChecking=accept-new \
  -o UserKnownHostsFile=/dev/null \
  -o LogLevel=ERROR \
  -o ConnectTimeout=15 \
  -o ServerAliveInterval=30"
SSH="ssh $SSH_OPTS root@$POD_HOST"

# ---- 1. Check SSH reachable ----
log "SSH check $POD_HOST:$POD_PORT"
if ! $SSH "echo OK" 2>/dev/null | grep -q OK; then
  log "ERROR: SSH unreachable"; exit 2
fi

# ---- 2. Install deps to /workspace/pypkgs (persistent) ----
log "Installing deps to /workspace/pypkgs (this persists across migrations)"
$SSH "mkdir -p /workspace/pypkgs /workspace/hf-cache && \
  pip install --quiet --no-cache-dir --target=/workspace/pypkgs \
    transformers==4.46.3 \
    peft==0.13.2 \
    trl==0.11.4 \
    bitsandbytes==0.49.2 \
    datasets==3.0.2 \
    accelerate==1.13.0 \
    liger-kernel==0.3.0 \
    rich \
    sentencepiece \
    protobuf 2>&1 | tail -5"
RC=$?
if [ "$RC" -ne 0 ]; then
  log "ERROR: pip install failed rc=$RC"; exit 3
fi

# ---- 3. Write /workspace/setup-env.sh (sourced by training scripts) ----
log "Writing /workspace/setup-env.sh"
$SSH "cat > /workspace/setup-env.sh <<'EOF'
# Auto-generated by setup-pod.sh — source me from training scripts.
# Adds persistent /workspace/pypkgs deps to Python path and points HF cache
# at the volume so downloaded models survive pod migrations too.
export PYTHONPATH=/workspace/pypkgs:\$PYTHONPATH
export HF_HOME=/workspace/hf-cache
export TRANSFORMERS_CACHE=/workspace/hf-cache
EOF
chmod +x /workspace/setup-env.sh"

# ---- 3.5. Strip torch+nvidia+triton from /workspace/pypkgs (let system torch win) ----
# pip install --target pulls in a NEWER torch than the pod image's system torch
# (2.4.1 + cu124 + torchvision 0.19.1) — and the system torchvision then breaks
# with "operator torchvision::nms does not exist". Fix: remove our local torch
# stack so the system one (which matches torchvision) takes precedence.
log "Removing torch/nvidia/triton from /workspace/pypkgs (use system torch instead)"
$SSH "rm -rf /workspace/pypkgs/torch /workspace/pypkgs/torchvision /workspace/pypkgs/torchaudio \
              /workspace/pypkgs/torch-* /workspace/pypkgs/torchvision-* /workspace/pypkgs/torchaudio-* \
              /workspace/pypkgs/nvidia* /workspace/pypkgs/triton /workspace/pypkgs/triton-* \
              /workspace/pypkgs/functorch /workspace/pypkgs/torchgen 2>&1 | tail -3"

# ---- 4. Verify critical imports work with the new PYTHONPATH ----
log "Verifying imports (trl / peft / bitsandbytes)"
VERIFY=$($SSH "source /workspace/setup-env.sh && \
  python3 -c 'from trl import SFTTrainer; import peft; import bitsandbytes; print(\"IMPORTS_OK\")' 2>&1")
echo "$VERIFY"
if ! echo "$VERIFY" | grep -q "IMPORTS_OK"; then
  log "ERROR: import verification failed"; exit 3
fi

log "SETUP OK"
echo "SETUP OK"
exit 0
